ALTER TABLE stair_configurations
    ADD COLUMN landing_depth_mm DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN room_width_mm DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN room_length_mm DOUBLE PRECISION NOT NULL DEFAULT 0;
