apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stair-platform.fullname" . }}-config
  labels:
    {{- include "stair-platform.labels" . | nindent 4 }}
data:
  STAIR_HTTP_ADDR: ":{{ .Values.service.port }}"
  STAIR_DB_MAX_CONNS: {{ .Values.database.maxConns | quote }}
  STAIR_DB_MIN_CONNS: {{ .Values.database.minConns | quote }}
  STAIR_DB_MAX_CONN_LIFETIME: {{ .Values.database.maxConnLifetime | quote }}
  STAIR_DB_MAX_CONN_IDLE_TIME: {{ .Values.database.maxConnIdleTime | quote }}
  STAIR_SESSION_TTL: {{ .Values.security.sessionTTL | quote }}
  STAIR_CORS_ORIGINS: {{ .Values.security.corsOrigins | quote }}
  STAIR_HSTS_ENABLED: {{ .Values.security.hstsEnabled | quote }}
  STAIR_COOKIE_SECURE: {{ .Values.security.cookieSecure | quote }}
  {{- if .Values.redis.addr }}
  STAIR_REDIS_ADDR: {{ .Values.redis.addr | quote }}
  {{- end }}
  {{- if .Values.monitoring.tracingEnabled }}
  STAIR_TRACING_ENABLED: "true"
  STAIR_TRACING_ENDPOINT: {{ .Values.monitoring.tracingEndpoint | quote }}
  STAIR_TRACING_SAMPLE_RATE: {{ .Values.monitoring.tracingSampleRate | quote }}
  {{- end }}
  {{- if .Values.debug.logging }}
  STAIR_DEBUG_LOGGING: "true"
  {{- end }}
