apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stair-platform.fullname" . }}-secrets
  labels:
    {{- include "stair-platform.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc | quote }}
  {{- if .Values.secretsKey }}
  secrets-key: {{ .Values.secretsKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.payments.stripeSecretKey }}
  stripe-secret-key: {{ .Values.payments.stripeSecretKey | b64enc | quote }}
  stripe-webhook-secret: {{ .Values.payments.stripeWebhookSecret | b64enc | quote }}
  {{- end }}
